# Generated by Django 5.2.3 on 2025-06-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emendas_app', '0005_programa_acaoorcamentaria_valor_empenhado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='nome',
            field=models.CharField(max_length=500),
        ),
    ]
