# Generated by Django 5.2.3 on 2025-06-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emendas_app', '0006_alter_programa_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emenda',
            name='cod_emenda',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
