# Generated by Django 5.2.3 on 2025-06-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emendas_app', '0007_alter_emenda_cod_emenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emenda',
            name='tipo',
            field=models.CharField(max_length=255),
        ),
    ]
