# Generated by Django 5.2.3 on 2025-06-30 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emendas_app', '0008_alter_emenda_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acaoorcamentaria',
            old_name='codigo_emenda',
            new_name='cod_emenda',
        ),
        migrations.RenameField(
            model_name='acaoorcamentaria',
            old_name='codigo_programa',
            new_name='cod_programa',
        ),
    ]
