# Generated by Django 5.2.3 on 2025-06-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emendas_app', '0009_rename_codigo_emenda_acaoorcamentaria_cod_emenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaoorcamentaria',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
