# Generated by Django 5.2.3 on 2025-06-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emendas_app', '0010_alter_acaoorcamentaria_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaoorcamentaria',
            name='cod_acao',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
